events {}

http {
    include mime.types;

    # Bắt truy cập HTTP (80) và chuyển hướng tự động sang HTTPS (443)
    server {
        listen 80;
        server_name attendance-pj.duckdns.org;
        return 301 https://$host$request_uri;
    }

    # Cấu hình máy chủ HTTPS chính
    server {
        listen 443 ssl;
        server_name attendance-pj.duckdns.org;

        # Đường dẫn tới chứng chỉ SSL đã lấy từ Let's Encrypt
        ssl_certificate /etc/letsencrypt/live/attendance-pj.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/attendance-pj.duckdns.org/privkey.pem;

        # Phục vụ Frontend + Đặt login.html làm trang bắt đầu
        location / {
            root /usr/share/nginx/html;
            index login.html;
            try_files $uri $uri/ =404;
        }

        # Lỗi Mixed Content: Khi trang web chạy bằng HTTPS, trình duyệt sẽ chặn đứng mọi kết nối HTTP gửi từ Frontend xuống Backend (port 8080). 
        # Để giải quyết bài toán này, cần cấu hình để Nginx làm "bảo vệ" cho cả Frontend và Backend.
        # Điều hướng API xuống Backend (Fix Mixed Content)
        location /api/v1/ {
            proxy_pass http://backend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}